# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='fans',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='concerner',
            field=models.ManyToManyField(through='app01.User2User', to='app01.UserInfo', verbose_name='关注'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Comment'),
        ),
    ]
